language: node_js
node_js:
- '12.16'
before_install:
- sudo apt-get install expect
- curl https://install.meteor.com | /bin/sh
- meteor update
- npm install
- npm i -g pm2-meteor
branches:
  only:
  - master
script:
  - "cd microservices/api"
  - "meteor npm install"
  - "cd src/.deploy"
  - "pm2-meteor deploy"
